# This is a basic workflow to help you get started with Actions

name: CI

on: push

env:
    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    
jobs:
  code_quality:
    runs-on: ubuntu-latest
    name: Checks with flake8, isort and possibly run tests
    container: python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
          pip install flake8 isort pytest requests flask flask-wtf
          ls -la
          flake8 .
          isort --check .
          py.test tests
